### ISSUE TITLE
Unable to view apple airport express and apple timecapsule device over zerotier

### ISSUE THREAD

**Issue by duckdegen** [mwarning/zerotier-openwrt#107]
Hello,

My main purpose for using zerotier is to use it as a backup tool to perform backups while on the road.

This means that I need my macbook to auto-discover other apple devices which are on my lan. 
This typically occurs over bonjour/mdns .

I have followed the instructions you have provided, and indeed I am able to connect to my LAN over the vpn, but apple autodiscovery fails.

Could you be so kind and help me figure out how to set this up?

**Comment by ogarcia** [comment]
It will not work because Zeroconf/Bonjour never leaves the local network.

If you have followed the steps in the wiki to configure the system, you will have a Zerotier network 172.28.28.0/24 and a local network or LAN (the one provided by your home router) 192.168.1.0/24. In the network 192.168.1.0/24 is where you have the Bonjour (I understand that it is a Time Capsule or similar for what you speak of the backup). Well, the Bonjour never leaves the 192.168.1.0/24 network so the autodiscovery packets will never reach the computers connected on the Zerotier 172.28.28.0/24 network.

My advice is that in your local network you configure your equipment with a fixed IP (or that the DHCP server always gives them the same IP) so that for example your Time Capsule always has the IP 192.168.1.100. From there you can configure your client so that instead of connecting to the service by name it does it by IP. This way it will never fail regardless of where you have connected your client.
