### ISSUE TITLE
'ifstatus ZT0' shows no IP

### ISSUE THREAD

**Issue by evilgreen** [mwarning/zerotier-openwrt#50]
Currently 'ifstatus ZT0' shows no IP.
As a result (I suppose) it is not possible to start _dropbear_ explicitly on ZT0 as it cannot obtain an IP address of the interface. There is also a cosmetic problem with no IP shown for ZT0 in the Interfaces section.
Will it be possible to fix that?

**Comment by mwarning** [comment]
The problem seems to be that ZT is started after dropbear. You could maybe use iptables to block any access to dropbear except by the address range used by ZT. Or you move ZT and dropbear into the same linux network namespace.

I assume this issue has gotten too old. So I going to close it. Feel free to reopen it if the problem persists.
